-- ============================================================
-- Migration: Settings & Quotes tables
-- Ejecutar en Supabase SQL Editor después de 001 y 002
-- ============================================================

-- ============================================================
-- 1. brand_settings — datos de empresa para cotizaciones
-- ============================================================
CREATE TABLE IF NOT EXISTS public.brand_settings (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL DEFAULT 'ROKKO',
  phone text NOT NULL DEFAULT '+56 9 XXXX XXXX',
  email text NOT NULL DEFAULT 'contacto@rokko.cl',
  city text NOT NULL DEFAULT 'Santiago',
  footer text NOT NULL DEFAULT 'Gracias por preferirnos.',
  bank_name text NOT NULL DEFAULT '',
  bank_account_type text NOT NULL DEFAULT '',
  bank_account_number text NOT NULL DEFAULT '',
  bank_account_holder text NOT NULL DEFAULT '',
  bank_account_rut text NOT NULL DEFAULT '',
  bank_account_email text NOT NULL DEFAULT '',
  payment_notes text NOT NULL DEFAULT '',
  updated_at timestamptz DEFAULT now()
);

-- Seed row (singleton — siempre editar id=1)
INSERT INTO public.brand_settings (id, name, phone, email, city, footer)
VALUES (1, 'ROKKO', '+56 9 XXXX XXXX', 'contacto@rokko.cl', 'Santiago', 'Gracias por preferirnos.')
ON CONFLICT (id) DO NOTHING;

ALTER TABLE public.brand_settings ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Public read brand_settings" ON public.brand_settings;
CREATE POLICY "Public read brand_settings"
ON public.brand_settings FOR SELECT TO public
USING (true);

DROP POLICY IF EXISTS "Admin write brand_settings" ON public.brand_settings;
CREATE POLICY "Admin write brand_settings"
ON public.brand_settings FOR INSERT TO authenticated
WITH CHECK (auth.jwt() ->> 'email' = 'admin@rokko.cl');

DROP POLICY IF EXISTS "Admin update brand_settings" ON public.brand_settings;
CREATE POLICY "Admin update brand_settings"
ON public.brand_settings FOR UPDATE TO authenticated
USING (auth.jwt() ->> 'email' = 'admin@rokko.cl')
WITH CHECK (auth.jwt() ->> 'email' = 'admin@rokko.cl');

DROP POLICY IF EXISTS "Admin delete brand_settings" ON public.brand_settings;
CREATE POLICY "Admin delete brand_settings"
ON public.brand_settings FOR DELETE TO authenticated
USING (auth.jwt() ->> 'email' = 'admin@rokko.cl');

-- ============================================================
-- 2. commercial_settings — reglas de negocio para cotización
-- ============================================================
CREATE TABLE IF NOT EXISTS public.commercial_settings (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  discount numeric(5,2) NOT NULL DEFAULT 0,
  wholesale_min integer NOT NULL DEFAULT 15,
  vat numeric(5,2) NOT NULL DEFAULT 19,
  validity integer NOT NULL DEFAULT 7,
  terms text NOT NULL DEFAULT '',
  updated_at timestamptz DEFAULT now()
);

INSERT INTO public.commercial_settings (id, discount, wholesale_min, vat, validity, terms)
VALUES (1, 0, 15, 19, 7, 'Valores con IVA incluido. Logo pecho incluido en precio base.')
ON CONFLICT (id) DO NOTHING;

ALTER TABLE public.commercial_settings ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Public read commercial_settings" ON public.commercial_settings;
CREATE POLICY "Public read commercial_settings"
ON public.commercial_settings FOR SELECT TO public
USING (true);

DROP POLICY IF EXISTS "Admin write commercial_settings" ON public.commercial_settings;
CREATE POLICY "Admin write commercial_settings"
ON public.commercial_settings FOR INSERT TO authenticated
WITH CHECK (auth.jwt() ->> 'email' = 'admin@rokko.cl');

DROP POLICY IF EXISTS "Admin update commercial_settings" ON public.commercial_settings;
CREATE POLICY "Admin update commercial_settings"
ON public.commercial_settings FOR UPDATE TO authenticated
USING (auth.jwt() ->> 'email' = 'admin@rokko.cl')
WITH CHECK (auth.jwt() ->> 'email' = 'admin@rokko.cl');

DROP POLICY IF EXISTS "Admin delete commercial_settings" ON public.commercial_settings;
CREATE POLICY "Admin delete commercial_settings"
ON public.commercial_settings FOR DELETE TO authenticated
USING (auth.jwt() ->> 'email' = 'admin@rokko.cl');

-- ============================================================
-- 3. quotes — cotizaciones emitidas por clientes
-- ============================================================
CREATE TABLE IF NOT EXISTS public.quotes (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  folio text UNIQUE NOT NULL,
  client_empresa text NOT NULL,
  client_rut text NOT NULL DEFAULT '',
  client_contacto text NOT NULL DEFAULT '',
  client_correo text NOT NULL DEFAULT '',
  client_telefono text NOT NULL DEFAULT '',
  client_observaciones text NOT NULL DEFAULT '',
  items jsonb NOT NULL DEFAULT '[]',
  total numeric(12,0) NOT NULL DEFAULT 0,
  status text NOT NULL DEFAULT 'pendiente',
  created_at timestamptz DEFAULT now()
);

ALTER TABLE public.quotes ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Public insert quotes" ON public.quotes;
CREATE POLICY "Public insert quotes"
ON public.quotes FOR INSERT TO public
WITH CHECK (true);

DROP POLICY IF EXISTS "Admin select quotes" ON public.quotes;
CREATE POLICY "Admin select quotes"
ON public.quotes FOR SELECT TO authenticated
USING (auth.jwt() ->> 'email' = 'admin@rokko.cl');

DROP POLICY IF EXISTS "Admin update quotes" ON public.quotes;
CREATE POLICY "Admin update quotes"
ON public.quotes FOR UPDATE TO authenticated
USING (auth.jwt() ->> 'email' = 'admin@rokko.cl')
WITH CHECK (auth.jwt() ->> 'email' = 'admin@rokko.cl');

DROP POLICY IF EXISTS "Admin delete quotes" ON public.quotes;
CREATE POLICY "Admin delete quotes"
ON public.quotes FOR DELETE TO authenticated
USING (auth.jwt() ->> 'email' = 'admin@rokko.cl');

-- Índice para búsqueda rápida por folio
CREATE INDEX IF NOT EXISTS idx_quotes_folio ON public.quotes (folio);
CREATE INDEX IF NOT EXISTS idx_quotes_status ON public.quotes (status);
CREATE INDEX IF NOT EXISTS idx_quotes_created ON public.quotes (created_at DESC);
